### ISSUE TITLE
Not sure if I am calling the function correctly

### ISSUE THREAD

**Issue by msyeung87** [msyeung87/msyeung87.github.io#1]
Hi Sung, I made an array of objects with key values for each individual cards (yeah I know it's repetitive and i will try to refactor that later).
I'm trying to get generate a random card from the deck of arrays so I used Math.floor(Math.random()) but I'm not sure if i'm calling it correctly.. 

here's my code,

```
function getRandom(min, max) {
  return Math.floor(Math.random() * (max - min) + min);
}

var deck = [
    { value: 1, url: "images/cards/ace_of_diamonds.png", count: false},
    { value: 1, url: "images/cards/ace_of_clubs.png", count: false},
    { value: 1, url: "images/cards/ace_of_hearts.png", count: false},
    { value: 1, url: "images/cards/ace_of_spades.png", count: false},
    { value: 2, url: "images/cards/2_of_diamonds.png", count: false},
    { value: 2, url: "images/cards/2_of_clubs.png", count: false},
    { value: 2, url: "images/cards/2_of_hearts.png", count: false},
    { value: 2, url: "images/cards/2_of_spades.png", count: false},
    { value: 3, url: "images/cards/3_of_diamonds.png", count: false}
];
```

there's 52 objects in the array but i won't list them all in here.

i'm trying to call the random object with a key, for instance the value
i can call certain part by "deck[5].value" but i want to get a random value from the array
i tried deck(getRandom).value,
deck[getRandom).value and many variations but it's not being able to call it. 
Is it something wrong with my code?

**Comment by msyeung87** [comment]
nevermind, i was able to figure it out. 
to get a random object or certain key in the array,
deck[getRandom(0,52)]      =     to get a random object
deck[getRandom(0,52)].value        =     to get a random key value within an object

**Comment by sungchoi** [comment]
To be precise:
deck[getRandom(0,52)] returns a random element from the deck array of length 52
deck[getRandom(0,52)].value returns the value of the random element that was returned from the deck array of length 52

@msyeung87 Nice work!
